var fs = require('fs');
data = [
{'word': 'Abuse', 'type': 'Noun', 'definition': 'To use wrongly or improperly'},
{'word': 'Adult', 'type': 'Noun ', 'definition': 'A person who is fully grown'},
{'word': 'Agent', 'type': 'Noun ', 'definition': 'A person who acts for another'},
{'word': 'Anger', 'type': 'Noun ', 'definition': 'Strong feeling of displeasure'},
{'word': 'Apple', 'type': 'Noun ', 'definition': 'The round fruit of a tree'},
{'word': 'Award', 'type': 'Noun ', 'definition': 'Something given in recognition'},
{'word': 'Basis', 'type': 'Noun ', 'definition': 'The foundation on which something is based'},
{'word': 'Beach', 'type': 'Noun ', 'definition': 'A stretch of sand or pebbles by the sea'},
{'word': 'Birth', 'type': 'Noun ', 'definition': 'The act of being born'},
{'word': 'Block', 'type': 'Noun ', 'definition': 'A solid piece of a substance'},
{'word': 'Blood', 'type': 'Noun ', 'definition': 'The fluid that circulates in the body'},
{'word': 'Board', 'type': 'Noun ', 'definition': 'A flat piece of wood'},
{'word': 'Brain', 'type': 'Noun ', 'definition': 'The organ of the body that controls thought'},
{'word': 'Bread', 'type': 'Noun ', 'definition': 'A baked food made from flour'},
{'word': 'Break', 'type': 'Noun ', 'definition': 'To separate into pieces'},
{'word': 'Brown', 'type': 'Noun ', 'definition': 'A dark yellowish-brown color'},
{'word': 'Buyer', 'type': 'Noun ', 'definition': 'A person who buys something'},
{'word': 'Cause', 'type': 'Noun ', 'definition': 'The reason for something'},
{'word': 'Chain', 'type': 'Noun ', 'definition': 'A series of things linked together'},
{'word': 'Chair', 'type': 'Noun ', 'definition': 'A seat for one person'},
{'word': 'Chest', 'type': 'Noun ', 'definition': 'The front part of the body'},
{'word': 'Chief', 'type': 'Noun ', 'definition': 'The most important person'},
{'word': 'Child', 'type': 'Noun ', 'definition': 'A young person'},
{'word': 'China', 'type': 'Noun ', 'definition': 'A country in Asia'},
{'word': 'Claim', 'type': 'Noun ', 'definition': 'To say that something is true'},
{'word': 'Class', 'type': 'Noun ', 'definition': 'A group of people who are the same age'},
{'word': 'Clock', 'type': 'Noun ', 'definition': 'An instrument for measuring time'},
{'word': 'Coach', 'type': 'Noun ', 'definition': 'A person who trains athletes'},
{'word': 'Coast', 'type': 'Noun ', 'definition': 'The edge of the land near the sea'},
{'word': 'Court', 'type': 'Noun ', 'definition': 'A place where a judge works'},
{'word': 'Cover', 'type': 'Noun ', 'definition': 'To put something over something else'},
{'word': 'Cream', 'type': 'Noun ', 'definition': 'A thick, yellowish-white substance'},
{'word': 'Crime', 'type': 'Noun ', 'definition': 'An illegal act'},
{'word': 'Cross', 'type': 'Noun ', 'definition': 'To move from one side to the other'},
{'word': 'Crowd', 'type': 'Noun ', 'definition': 'A large number of people'},
{'word': 'Crown', 'type': 'Noun ', 'definition': 'A gold or silver circle worn on the head'},
{'word': 'Cycle', 'type': 'Noun ', 'definition': 'A series of events that happen over and over'},
{'word': 'Dance', 'type': 'Noun ', 'definition': 'To move your body to music'},
{'word': 'Death', 'type': 'Noun ', 'definition': 'The end of life'},
{'word': 'Depth', 'type': 'Noun ', 'definition': 'The distance from the top to the bottom'},
{'word': 'Doubt', 'type': 'Noun ', 'definition': 'To be uncertain about something'},
{'word': 'Draft', 'type': 'Noun ', 'definition': 'A preliminary version of a document'},
{'word': 'Drama', 'type': 'Noun ', 'definition': 'A story that is acted out'},
{'word': 'Dream', 'type': 'Noun ', 'definition': 'A series of thoughts, images, and feelings'},
{'word': 'Dress', 'type': 'Noun ', 'definition': 'a one-piece garment worn by women and girls that covers the body and extends down over the legs'},
{'word': 'Drink', 'type': 'Noun ', 'definition': 'A liquid that people and animals drink'},
{'word': 'Drive', 'type': 'Noun ', 'definition': 'To move a vehicle'},
{'word': 'Earth', 'type': 'Noun ', 'definition': 'The planet on which we live'},
{'word': 'Enemy', 'type': 'Noun ', 'definition': 'A person who hates another'},
{'word': 'Entry', 'type': 'Noun ', 'definition': 'The act of entering'},
{'word': 'Error', 'type': 'Noun ', 'definition': 'A mistake'},
{'word': 'Event', 'type': 'Noun ', 'definition': 'Something that happens'},
{'word': 'Faith', 'type': 'Noun ', 'definition': 'Complete trust or confidence in someone'},
{'word': 'Fault', 'type': 'Noun ', 'definition': 'A mistake'},
{'word': 'Field', 'type': 'Noun ', 'definition': 'A piece of land'},
{'word': 'Fight', 'type': 'Noun ', 'definition': 'To struggle with another person'},
{'word': 'Final', 'type': 'Noun ', 'definition': 'Coming at the end'},
{'word': 'Floor', 'type': 'Noun ', 'definition': 'The bottom surface of a room'},
{'word': 'Focus', 'type': 'Noun ', 'definition': 'The center of interest'},
{'word': 'Force', 'type': 'Noun ', 'definition': 'The power to move or influence something'},
{'word': 'Frame', 'type': 'Noun ', 'definition': 'A structure that holds something in place'},
{'word': 'Frank', 'type': 'Noun ', 'definition': 'Honest'},
{'word': 'Front', 'type': 'Noun ', 'definition': 'The side of something that is in front'},
{'word': 'Fruit', 'type': 'Noun ', 'definition': 'The seed-bearing part of a plant'},
{'word': 'Glass', 'type': 'Noun ', 'definition': 'A transparent solid'},
{'word': 'Grant', 'type': 'Noun ', 'definition': 'To give or allow something'},
{'word': 'Grass', 'type': 'Noun ', 'definition': 'A plant with long, green leaves'},
{'word': 'Green', 'type': 'Noun ', 'definition': 'A color like that of grass'},
{'word': 'Group', 'type': 'Noun ', 'definition': 'A number of things or people'},
{'word': 'Guide', 'type': 'Noun ', 'definition': 'A person who leads others'},
{'word': 'Heart', 'type': 'Noun ', 'definition': 'The organ that pumps blood'},
{'word': 'Horse', 'type': 'Noun ', 'definition': 'A large animal with four legs'},
{'word': 'Hotel', 'type': 'Noun ', 'definition': 'A building where people can stay'},
{'word': 'House', 'type': 'Noun ', 'definition': 'A building for people to live in'},
{'word': 'Image', 'type': 'Noun ', 'definition': 'A picture in the mind'},
{'word': 'Index', 'type': 'Noun ', 'definition': 'A list of names and page numbers'},
{'word': 'Input', 'type': 'Noun ', 'definition': 'Information put into a computer'},
{'word': 'Issue', 'type': 'Noun ', 'definition': 'A problem'},
{'word': 'Japan', 'type': 'Noun ', 'definition': 'An island country in Asia'},
{'word': 'Jones', 'type': 'Noun ', 'definition': 'A surname'},
{'word': 'Judge', 'type': 'Noun ', 'definition': 'A person who decides cases in court'},
{'word': 'Knife', 'type': 'Noun ', 'definition': 'A tool with a sharp blade'},
{'word': 'Layer', 'type': 'Noun ', 'definition': 'A flat, thin sheet'},
{'word': 'Level', 'type': 'Noun ', 'definition': 'The height of something'},
{'word': 'Lewis', 'type': 'Noun ', 'definition': 'A surname'},
{'word': 'Light', 'type': 'Noun ', 'definition': 'A form of energy that can be seen'},
{'word': 'Limit', 'type': 'Noun ', 'definition': 'The greatest amount or degree'},
{'word': 'Lunch', 'type': 'Noun ', 'definition': 'A meal eaten in the middle of the day'},
{'word': 'Major', 'type': 'Noun ', 'definition': 'A person who has graduated from college'},
{'word': 'March', 'type': 'Noun ', 'definition': 'The third month of the year'},
{'word': 'Metal', 'type': 'Noun ', 'definition': 'A solid material that is shiny'},
{'word': 'Model', 'type': 'Noun ', 'definition': 'A person who poses for a photographer'},
{'word': 'Money', 'type': 'Noun ', 'definition': 'A medium of exchange'},
{'word': 'Month', 'type': 'Noun ', 'definition': 'A period of 30 days'},
{'word': 'Motor', 'type': 'Noun ', 'definition': 'A machine that converts energy into motion'},
{'word': 'Mouth', 'type': 'Noun ', 'definition': 'The opening at the end of the throat'},
{'word': 'Music', 'type': 'Noun ', 'definition': 'Sounds that are organized in a special way'},
{'word': 'Night', 'type': 'Noun ', 'definition': 'The time between sunset and sunrise'},
{'word': 'Noise', 'type': 'Noun ', 'definition': 'A sound that is loud or unpleasant'},
{'word': 'North', 'type': 'Noun ', 'definition': 'The direction opposite to south'},
{'word': 'Novel', 'type': 'Noun ', 'definition': 'A long work of fiction'},
{'word': 'Nurse', 'type': 'Noun ', 'definition': 'A person who cares for sick people'},
{'word': 'Offer', 'type': 'Noun ', 'definition': 'To give something to someone'},
{'word': 'Order', 'type': 'Noun ', 'definition': 'A command'},
{'word': 'Other', 'type': 'Noun ', 'definition': 'Different from one already mentioned'},
{'word': 'Owner', 'type': 'Noun ', 'definition': 'A person who owns something'},
{'word': 'Panel', 'type': 'Noun ', 'definition': 'A group of people who meet to discuss something'},
{'word': 'Paper', 'type': 'Noun ', 'definition': 'A material made from wood pulp'},
{'word': 'Party', 'type': 'Noun ', 'definition': 'A group of people who have gathered'},
{'word': 'Peace', 'type': 'Noun ', 'definition': 'Freedom from war'},
{'word': 'Phase', 'type': 'Noun ', 'definition': 'A part of a process'},
{'word': 'Phone', 'type': 'Noun ', 'definition': 'A device for making and receiving calls'},
{'word': 'Piece', 'type': 'Noun ', 'definition': 'A part of something'},
{'word': 'Pilot', 'type': 'Noun ', 'definition': 'A person who flies an airplane'},
{'word': 'Pitch', 'type': 'Noun ', 'definition': 'A slope'},
{'word': 'Place', 'type': 'Noun ', 'definition': 'A particular position'},
{'word': 'Plane', 'type': 'Noun ', 'definition': 'A flat surface with no edges'},
{'word': 'Plant', 'type': 'Noun ', 'definition': 'A living thing that grows in the ground'},
{'word': 'Plate', 'type': 'Noun ', 'definition': 'A flat dish'},
{'word': 'Point', 'type': 'Noun ', 'definition': 'A small piece of something'},
{'word': 'Pound', 'type': 'Noun ', 'definition': 'A unit of weight'},
{'word': 'Power', 'type': 'Noun ', 'definition': 'The ability to do something'},
{'word': 'Press', 'type': 'Noun ', 'definition': 'To apply force to something'},
{'word': 'Price', 'type': 'Noun ', 'definition': 'The amount of money that something costs'},
{'word': 'Pride', 'type': 'Noun ', 'definition': 'A feeling of pleasure in oneself'},
{'word': 'Prize', 'type': 'Noun ', 'definition': 'A reward given for winning a contest'},
{'word': 'Proof', 'type': 'Noun ', 'definition': 'Evidence that something is true'},
{'word': 'Queen', 'type': 'Noun ', 'definition': 'The wife of a king'},
{'word': 'Radio', 'type': 'Noun ', 'definition': 'A device for receiving and sending signals'},
{'word': 'Range', 'type': 'Noun ', 'definition': 'A series of related things'},
{'word': 'Ratio', 'type': 'Noun ', 'definition': 'A comparison of two numbers'},
{'word': 'Reply', 'type': 'Noun ', 'definition': 'To say something in response to a question'},
{'word': 'Right', 'type': 'Noun ', 'definition': 'The opposite of left'},
{'word': 'River', 'type': 'Noun ', 'definition': 'A large stream of water'},
{'word': 'Round', 'type': 'Noun ', 'definition': 'A circular shape'},
{'word': 'Route', 'type': 'Noun ', 'definition': 'A way to get from one place to another'},
{'word': 'Rugby', 'type': 'Noun ', 'definition': 'A game played with an oval ball'},
{'word': 'Scale', 'type': 'Noun ', 'definition': 'A device for measuring weight'},
{'word': 'Scene', 'type': 'Noun ', 'definition': 'A place where something happens'},
{'word': 'Scope', 'type': 'Noun ', 'definition': 'The range of something'},
{'word': 'Score', 'type': 'Noun ', 'definition': 'A number that shows how well someone has done'},
{'word': 'Sense', 'type': 'Noun ', 'definition': 'The ability to feel, hear, see, smell, or taste'},
{'word': 'Shape', 'type': 'Noun ', 'definition': 'The form of something'},
{'word': 'Share', 'type': 'Noun ', 'definition': 'To divide something'},
{'word': 'Sheep', 'type': 'Noun ', 'definition': 'A domesticated animal'},
{'word': 'Sheet', 'type': 'Noun ', 'definition': 'A large piece of paper'},
{'word': 'Shift', 'type': 'Noun ', 'definition': 'To move from one place to another'},
{'word': 'Shirt', 'type': 'Noun ', 'definition': 'A piece of clothing for the upper part of the body'},
{'word': 'Shock', 'type': 'Noun ', 'definition': 'A sudden feeling of surprise'},
{'word': 'Sight', 'type': 'Noun ', 'definition': 'The ability to see'},
{'word': 'Simon', 'type': 'Noun ', 'definition': 'A disciple of Jesus'},
{'word': 'Skill', 'type': 'Noun ', 'definition': 'The ability to do something well'},
{'word': 'Sleep', 'type': 'Noun ', 'definition': 'A state of rest'},
{'word': 'Smile', 'type': 'Noun ', 'definition': 'A facial expression'},
{'word': 'Smith', 'type': 'Noun ', 'definition': 'A person who makes things from metal'},
{'word': 'Smoke', 'type': 'Noun ', 'definition': 'A substance that is produced when something burns'},
{'word': 'Sound', 'type': 'Noun ', 'definition': 'A noise that can be heard'},
{'word': 'South', 'type': 'Noun ', 'definition': 'The direction opposite to north'},
{'word': 'Space', 'type': 'Noun ', 'definition': 'The area around something'},
{'word': 'Speed', 'type': 'Noun ', 'definition': 'The rate at which something moves'},
{'word': 'Spite', 'type': 'Noun ', 'definition': 'A desire to hurt someone'},
{'word': 'Sport', 'type': 'Noun ', 'definition': 'A game or activity that is played for fun'},
{'word': 'Squad', 'type': 'Noun ', 'definition': 'A group of people who work together'},
{'word': 'Staff', 'type': 'Noun ', 'definition': 'A group of people who work together'},
{'word': 'Stage', 'type': 'Noun ', 'definition': 'A part of a process'},
{'word': 'Start', 'type': 'Noun ', 'definition': 'To begin something'},
{'word': 'State', 'type': 'Noun ', 'definition': 'A country'},
{'word': 'Steam', 'type': 'Noun ', 'definition': 'A gas that is produced when something is heated'},
{'word': 'Steel', 'type': 'Noun ', 'definition': 'A metal that is very strong'},
{'word': 'Stock', 'type': 'Noun ', 'definition': 'A supply of something'},
{'word': 'Stone', 'type': 'Noun ', 'definition': 'A hard substance that is found in the ground'},
{'word': 'Store', 'type': 'Noun ', 'definition': 'A place where things are kept'},
{'word': 'Study', 'type': 'Noun ', 'definition': 'To learn about something'},
{'word': 'Stuff', 'type': 'Noun ', 'definition': 'Things'},
{'word': 'Style', 'type': 'Noun ', 'definition': 'A particular way of doing something'},
{'word': 'Sugar', 'type': 'Noun ', 'definition': 'A sweet substance that is found in plants'},
{'word': 'Table', 'type': 'Noun ', 'definition': 'A piece of furniture'},
{'word': 'Taste', 'type': 'Noun ', 'definition': 'The ability to taste'},
{'word': 'Terry', 'type': 'Noun ', 'definition': 'A cloth made from cotton'},
{'word': 'Theme', 'type': 'Noun ', 'definition': 'A subject that is discussed'},
{'word': 'Thing', 'type': 'Noun ', 'definition': 'A person, place, or thing'},
{'word': 'Title', 'type': 'Noun ', 'definition': 'A name'},
{'word': 'Total', 'type': 'Noun ', 'definition': 'The whole amount'},
{'word': 'Touch', 'type': 'Noun ', 'definition': 'To feel something with your hand'},
{'word': 'Tower', 'type': 'Noun ', 'definition': 'A tall building'},
{'word': 'Track', 'type': 'Noun ', 'definition': 'A line that is used by trains'},
{'word': 'Trade', 'type': 'Noun ', 'definition': 'To exchange goods'},
{'word': 'Train', 'type': 'Noun ', 'definition': 'A vehicle that runs on rails'},
{'word': 'Trend', 'type': 'Noun ', 'definition': 'A general direction in which something is developing'},
{'word': 'Trial', 'type': 'Noun ', 'definition': 'A test'},
{'word': 'Trust', 'type': 'Noun ', 'definition': 'To believe in someone'},
{'word': 'Truth', 'type': 'Noun ', 'definition': 'Something that is true'},
{'word': 'Uncle', 'type': 'Noun ', 'definition': 'The brother of your father or mother'},
{'word': 'Union', 'type': 'Noun ', 'definition': 'A group of people who work together'},
{'word': 'Unity', 'type': 'Noun ', 'definition': 'The state of being united'},
{'word': 'Value', 'type': 'Noun ', 'definition': 'The amount of money that something is worth'},
{'word': 'Video', 'type': 'Noun ', 'definition': 'A recording of moving pictures'},
{'word': 'Visit', 'type': 'Noun ', 'definition': 'To go to see someone'},
{'word': 'Voice', 'type': 'Noun ', 'definition': 'The sound that comes from your mouth when you speak'},
{'word': 'Waste', 'type': 'Noun ', 'definition': 'To use something in a way that is not useful'},
{'word': 'Watch', 'type': 'Noun ', 'definition': 'A small clock that you wear on your wrist'},
{'word': 'Water', 'type': 'Noun ', 'definition': 'A liquid that is found in rivers, lakes, and the sea'},
{'word': 'While', 'type': 'Noun ', 'definition': 'At the same time'},
{'word': 'White', 'type': 'Noun ', 'definition': 'The colour of snow'},
{'word': 'Whole', 'type': 'Noun ', 'definition': 'The entire amount'},
{'word': 'Woman', 'type': 'Noun' , 'definition': 'an adult female human being'},
{'word': 'World', 'type': 'Noun' , 'definition': 'the earth, together with all of its countries and peoples'},
{'word': 'Youth', 'type': 'Noun' , 'definition': 'the period between childhood and adult age'},
{'word': 'About', 'type': 'Adverb', 'definition': 'in the direction of'},
{'word': 'Above', 'type': 'Adverb', 'definition': 'in or to a higher place'},
{'word': 'After', 'type': 'Adverb', 'definition': 'at a later time'},
{'word': 'Again', 'type': 'Adverb', 'definition': 'one more time'},
{'word': 'Ahead', 'type': 'Adverb', 'definition': 'in or to a forward direction'},
{'word': 'Along', 'type': 'Adverb', 'definition': 'in or to a line or direction'},
{'word': 'Among', 'type': 'Adverb', 'definition': 'in or to a group'},
{'word': 'Apart', 'type': 'Adverb', 'definition': 'in or to a separate place'},
{'word': 'Aside', 'type': 'Adverb', 'definition': 'in or to a place that is not near'},
{'word': 'Admit', 'type': 'Verb', 'definition': 'to allow someone to enter'},
{'word': 'Adopt', 'type': 'Verb', 'definition': 'to take someone else’s child as your own'},
{'word': 'Agree', 'type': 'Verb', 'definition':  'to have the same opinion as someone else'},
{'word': 'Allow', 'type': 'Verb', 'definition': 'to let someone do something'},
{'word': 'Alter', 'type': 'Verb', 'definition': 'to change something'},
{'word': 'Apply', 'type': 'Verb', 'definition': 'to use something'},
{'word': 'Argue', 'type': 'Verb', 'definition': 'to have a disagreement with someone'},
{'word': 'Arise', 'type': 'Verb', 'definition': 'to begin to exist'},
{'word': 'Avoid', 'type': 'Verb', 'definition': 'to stay away from something'},
{'word': 'Begin', 'type': 'Verb', 'definition': 'to start something'},
{'word': 'Blame', 'type': 'Verb', 'definition': 'to say that someone is responsible for something'},
{'word': 'Break', 'type': 'Verb', 'definition': 'to separate into two or more pieces'},
{'word': 'Bring', 'type': 'Verb', 'definition': 'to take something to a place'},
{'word': 'Build', 'type': 'Verb', 'definition': 'to make something'},
{'word': 'Burst', 'type': 'Verb', 'definition': 'to break open suddenly'},
{'word': 'Carry', 'type': 'Verb', 'definition': 'to take something with you'},
{'word': 'Catch', 'type': 'Verb', 'definition': 'to get something that is thrown'},
{'word': 'Cause', 'type': 'Verb', 'definition': 'to make something happen'},
{'word': 'Check', 'type': 'Verb', 'definition': 'to look at something carefully'},
{'word': 'Claim', 'type': 'Verb', 'definition': 'to say that something is true'},
{'word': 'Clean', 'type': 'Verb', 'definition': 'to make something free from dirt'},
{'word': 'Clear', 'type': 'Verb', 'definition': 'to make something free from clouds'},
{'word': 'Climb', 'type': 'Verb', 'definition': 'to go up something, such as a mountain'},
{'word': 'Close', 'type': 'Verb', 'definition': 'to make something shut'},
{'word': 'Count', 'type': 'Verb', 'definition': 'to say the numbers in order'},
{'word': 'Cover', 'type': 'Verb', 'definition': 'to put something over something else'},
{'word': 'Cross', 'type': 'Verb', 'definition': 'to go across something'},
{'word': 'Dance', 'type': 'Verb', 'definition': 'to move your body to music'},
{'word': 'Doubt', 'type': 'Verb', 'definition': 'to not be sure about something'},
{'word': 'Drink', 'type': 'Verb', 'definition': 'to put a liquid into your mouth'},
{'word': 'Drive', 'type': 'Verb', 'definition': 'to control a vehicle'},
{'word': 'Enjoy', 'type': 'Verb', 'definition': 'to like something'},
{'word': 'Enter', 'type': 'Verb', 'definition': 'to go into a place'},
{'word': 'Exist', 'type': 'Verb', 'definition': 'to be alive'},
{'word': 'Fight', 'type': 'Verb', 'definition': 'to hit someone'},
{'word': 'Focus', 'type': 'Verb', 'definition': 'to think about something'},
{'word': 'Force', 'type': 'Verb', 'definition': 'to make someone do something'},
{'word': 'Guess', 'type': 'Verb', 'definition': 'to think that something is true'},
{'word': 'Imply', 'type': 'Verb', 'definition': 'to suggest that something is true'},
{'word': 'Issue', 'type': 'Verb', 'definition': 'to give something to someone'},
{'word': 'Judge', 'type': 'Verb', 'definition': 'to decide if someone is guilty'},
{'word': 'Laugh', 'type': 'Verb', 'definition': 'to make a sound with your mouth open'},
{'word': 'Learn', 'type': 'Verb', 'definition': 'to get knowledge'},
{'word': 'Leave', 'type': 'Verb', 'definition': 'to go away from a place'},
{'word': 'Limit', 'type': 'Verb', 'definition': 'to set a limit on something'},
{'word': 'Marry', 'type': 'Verb', 'definition': 'to get married'},
{'word': 'Match', 'type': 'Verb', 'definition': 'to be the same as something'},
{'word': 'Occur', 'type': 'Verb', 'definition': 'to happen'},
{'word': 'Offer', 'type': 'Verb', 'definition': 'to give something to someone'},
{'word': 'Order', 'type': 'Verb', 'definition': 'to tell someone to do something'},
{'word': 'Phone', 'type': 'Verb', 'definition': 'to talk to someone on the telephone'},
{'word': 'Place', 'type': 'Verb', 'definition': 'to put something in a particular position'},
{'word': 'Point', 'type': 'Verb', 'definition': 'to show someone something'},
{'word': 'Press', 'type': 'Verb', 'definition': 'to push something'},
{'word': 'Prove', 'type': 'Verb', 'definition': 'to show that something is true'},
{'word': 'Raise', 'type': 'Verb', 'definition': 'to lift something'},
{'word': 'Reach', 'type': 'Verb', 'definition': 'to get to something'},
{'word': 'Refer', 'type': 'Verb', 'definition': 'to talk about something'},
{'word': 'Relax', 'type': 'Verb', 'definition': 'to stop working'},
{'word': 'Serve', 'type': 'Verb', 'definition': 'to give food to someone'},
{'word': 'Shall', 'type': 'Verb', 'definition': 'to say that something will happen'},
{'word': 'Share', 'type': 'Verb', 'definition': 'to give something to someone'},
{'word': 'Shift', 'type': 'Verb', 'definition': 'to move something'},
{'word': 'Shoot', 'type': 'Verb', 'definition': 'to fire a gun'},
{'word': 'Sleep', 'type': 'Verb', 'definition': 'to rest'},
{'word': 'Solve', 'type': 'Verb', 'definition': 'to find the answer to a problem'},
{'word': 'Sound', 'type': 'Verb', 'definition': 'to make a noise'},
{'word': 'Speak', 'type': 'Verb', 'definition': 'to say words'},
{'word': 'Spend', 'type': 'Verb', 'definition': 'to use money'},
{'word': 'Split', 'type': 'Verb', 'definition': 'to break something into two parts'},
{'word': 'Stand', 'type': 'Verb', 'definition': 'to be in an upright position'},
{'word': 'Start', 'type': 'Verb', 'definition': 'to begin something'},
{'word': 'State', 'type': 'Verb', 'definition': 'to say something'},
{'word': 'Stick', 'type': 'Verb', 'definition': 'to put something on something else'},
{'word': 'Study', 'type': 'Verb', 'definition': 'to learn about something'},
{'word': 'Teach', 'type': 'Verb', 'definition': 'to give knowledge to someone'},
{'word': 'Thank', 'type': 'Verb', 'definition': 'to say that you are grateful to someone'},
{'word': 'Think', 'type': 'Verb', 'definition': 'to have an opinion about something'},
{'word': 'Throw', 'type': 'Verb', 'definition': 'to move something through the air'},
{'word': 'Touch', 'type': 'Verb', 'definition': 'to put your hand on something'},
{'word': 'Train', 'type': 'Verb', 'definition': 'to teach someone to do something'},
{'word': 'Treat', 'type': 'Verb', 'definition': 'to give someone something'},
{'word': 'Trust', 'type': 'Verb', 'definition': 'to believe that someone is honest'},
{'word': 'Visit', 'type': 'Verb', 'definition': 'to go to see someone'},
{'word': 'Voice', 'type': 'Verb', 'definition': 'to speak'},
{'word': 'Waste', 'type': 'Verb', 'definition': 'to use something in a way that is not useful'},
{'word': 'Watch', 'type': 'Verb', 'definition': 'to look at something'},
{'word': 'Worry', 'type': 'Verb', 'definition': 'to feel anxious about something'},
{'word': 'Would', 'type': 'Verb', 'definition': 'to say that something is possible'},
{'word': 'Write', 'type': 'Verb', 'definition': 'to put words on paper'},
{'word': 'Above', 'type': 'Adjectives', 'definition': 'higher than something else'},
{'word': 'Acute', 'type': 'Adjectives', 'definition': 'sharp'},
{'word': 'Alive', 'type': 'Adjectives', 'definition': 'living'},
{'word': 'Alone', 'type': 'Adjectives', 'definition': 'without anyone else'},
{'word': 'Angry', 'type': 'Adjectives', 'definition': 'feeling or showing anger'},
{'word': 'Aware', 'type': 'Adjectives' , 'definition': 'knowing about something'},
{'word': 'Awful', 'type': 'Adjectives', 'definition': 'very bad'},
{'word': 'Basic', 'type': 'Adjectives', 'definition': 'simple'},
{'word': 'Black', 'type': 'Adjectives', 'definition': 'dark in colour'},
{'word': 'Blind', 'type': 'Adjectives', 'definition': 'unable to see'},
{'word': 'Brave', 'type': 'Adjectives', 'definition': 'not afraid of danger'},
{'word': 'Brief', 'type': 'Adjectives', 'definition': 'lasting for a short time'},
{'word': 'Broad', 'type': 'Adjectives', 'definition': 'wide'},
{'word': 'Brown', 'type': 'Adjectives', 'definition': 'dark in colour'},
{'word': 'Cheap', 'type': 'Adjectives', 'definition': 'not expensive'},
{'word': 'Chief', 'type': 'Adjectives', 'definition': 'most important'},
{'word': 'Civil', 'type': 'Adjectives', 'definition': 'relating to ordinary people'},
{'word': 'Clean', 'type': 'Adjectives', 'definition': 'free from dirt'},
{'word': 'Clear', 'type': 'Adjectives', 'definition': 'easy to see or understand'},
{'word': 'Close', 'type': 'Adjectives', 'definition': 'near'},
{'word': 'Crazy', 'type': 'Adjectives', 'definition': 'mentally ill'},
{'word': 'Daily', 'type': 'Adjectives', 'definition': 'happening every day'},
{'word': 'Dirty', 'type': 'Adjectives', 'definition': 'covered in dirt'},
{'word': 'Early', 'type': 'Adjectives', 'definition': 'happening before the usual time'},
{'word': 'Empty', 'type': 'Adjectives', 'definition': 'having nothing in it'},
{'word': 'Equal', 'type': 'Adjectives', 'definition': 'the same'},
{'word': 'Exact', 'type': 'Adjectives', 'definition': 'exactly correct'},
{'word': 'Extra', 'type': 'Adjectives', 'definition': 'more than usual'},
{'word': 'Faint', 'type': 'Adjectives', 'definition': 'weak'},
{'word': 'False', 'type': 'Adjectives', 'definition': 'not true'},
{'word': 'Fifth', 'type': 'Adjectives', 'definition': 'the fifth in a series'},
{'word': 'Final', 'type': 'Adjectives', 'definition': 'happening at the end'},
{'word': 'First', 'type': 'Adjectives', 'definition': 'happening before all others'},
{'word': 'Fresh', 'type': 'Adjectives', 'definition': 'not used before'},
{'word': 'Front', 'type': 'Adjectives', 'definition': 'at the front'},
{'word': 'Funny', 'type': 'Adjectives', 'definition': 'causing laughter'},
{'word': 'Giant', 'type': 'Adjectives', 'definition': 'very large'},
{'word': 'Grand', 'type': 'Adjectives', 'definition': 'very large'},
{'word': 'Great', 'type': 'Adjectives', 'definition': 'very good'},
{'word': 'Green', 'type': 'Adjectives', 'definition': 'a colour like grass'},
{'word': 'Gross', 'type': 'Adjectives', 'definition': 'very bad'},
{'word': 'Happy', 'type': 'Adjectives', 'definition': 'feeling or showing pleasure'},
{'word': 'Harsh', 'type': 'Adjectives', 'definition': 'unpleasantly rough'},
{'word': 'Heavy', 'type': 'Adjectives', 'definition': 'not light'},
{'word': 'Human', 'type': 'Adjectives', 'definition': 'relating to people'},
{'word': 'Ideal', 'type': 'Adjectives', 'definition': 'perfect'},
{'word': 'Inner', 'type': 'Adjectives', 'definition': 'inside'},
{'word': 'Joint', 'type': 'Adjectives', 'definition': 'shared by two or more people'},
{'word': 'Large', 'type': 'Adjectives', 'definition': 'big'},
{'word': 'Legal', 'type': 'Adjectives', 'definition': 'allowed by law'},
{'word': 'Level', 'type': 'Adjectives', 'definition': 'flat'},
{'word': 'Light', 'type': 'Adjectives', 'definition': 'not heavy'},
{'word': 'Local', 'type': 'Adjectives', 'definition': 'relating to a particular area'},
{'word': 'Loose', 'type': 'Adjectives', 'definition': 'not tight'},
{'word': 'Lucky', 'type': 'Adjectives', 'definition': 'having good luck'},
{'word': 'Magic', 'type': 'Adjectives', 'definition': 'using magic'},
{'word': 'Major', 'type': 'Adjectives', 'definition': 'important'},
{'word': 'Minor', 'type': 'Adjectives', 'definition': 'less important'},
{'word': 'Moral', 'type': 'Adjectives', 'definition': 'relating to right and wrong'},
{'word': 'Naked', 'type': 'Adjectives', 'definition': 'not wearing clothes'},
{'word': 'Nasty', 'type': 'Adjectives', 'definition': 'very unpleasant'},
{'word': 'Naval', 'type': 'Adjectives', 'definition': 'relating to ships'},
{'word': 'Other', 'type': 'Adjectives', 'definition': 'different from one already mentioned'},
{'word': 'Outer', 'type': 'Adjectives', 'definition': 'outside'},
{'word': 'Plain', 'type': 'Adjectives', 'definition': 'not decorated'},
{'word': 'Prime', 'type': 'Adjectives', 'definition': 'most important'},
{'word': 'Prior', 'type': 'Adjectives', 'definition': 'happening before'},
{'word': 'Proud', 'type': 'Adjectives', 'definition': 'feeling pleasure because of something you have done'},
{'word': 'Quick', 'type': 'Adjectives', 'definition': 'happening or done quickly'},
{'word': 'Quiet', 'type': 'Adjectives', 'definition': 'not making a lot of noise'},
{'word': 'Rapid', 'type': 'Adjectives', 'definition': 'moving or happening very quickly'},
{'word': 'Ready', 'type': 'Adjectives', 'definition': 'prepared'},
{'word': 'Right', 'type': 'Adjectives', 'definition': 'correct'},
{'word': 'Roman', 'type': 'Adjectives', 'definition': 'relating to ancient Rome'},
{'word': 'Rough', 'type': 'Adjectives', 'definition': 'not smooth'},
{'word': 'Round', 'type': 'Adjectives', 'definition': 'shaped like a circle'},
{'word': 'Royal', 'type': 'Adjectives', 'definition': 'relating to a king or queen'},
{'word': 'Rural', 'type': 'Adjectives', 'definition': 'relating to the countryside'},
{'word': 'Sharp', 'type': 'Adjectives', 'definition': 'having a pointed edge'},
{'word': 'Sheer', 'type': 'Adjectives', 'definition': 'complete'},
{'word': 'Short', 'type': 'Adjectives', 'definition': 'not tall'},
{'word': 'Silly', 'type': 'Adjectives', 'definition': 'foolish'},
{'word': 'Sixth', 'type': 'Adjectives', 'definition': 'the sixth in a series'},
{'word': 'Small', 'type': 'Adjectives', 'definition': 'not big'},
{'word': 'Smart', 'type': 'Adjectives', 'definition': 'clever'},
{'word': 'Solid', 'type': 'Adjectives', 'definition': 'not liquid'},
{'word': 'Sorry', 'type': 'Adjectives', 'definition': 'feeling regret'},
{'word': 'Spare', 'type': 'Adjectives', 'definition': 'not being used'},
{'word': 'Steep', 'type': 'Adjectives', 'definition': 'having a very steep slope'},
{'word': 'Still', 'type': 'Adjectives', 'definition': 'not moving'},
{'word': 'Super', 'type': 'Adjectives', 'definition': 'very good'},
{'word': 'Sweet', 'type': 'Adjectives', 'definition': 'tasting of sugar'},
{'word': 'Thick', 'type': 'Adjectives', 'definition': 'not thin'},
{'word': 'Third', 'type': 'Adjectives', 'definition': 'the third in a series'},
{'word': 'Tight', 'type': 'Adjectives', 'definition': 'not loose'},
{'word': 'Total', 'type': 'Adjectives', 'definition': 'complete'},
{'word': 'Tough', 'type': 'Adjectives', 'definition': 'not easily damaged'},
{'word': 'Upper', 'type': 'Adjectives', 'definition': 'higher up'},
{'word': 'Upset', 'type': 'Adjectives', 'definition': 'feeling worried or unhappy'},
{'word': 'Urban', 'type': 'Adjectives', 'definition': 'relating to cities'},
{'word': 'Usual', 'type': 'Adjectives', 'definition': 'happening all the time'},
{'word': 'Vague', 'type': 'Adjectives', 'definition': 'not clear'},
{'word': 'Valid', 'type': 'Adjectives', 'definition': 'correct'},
{'word': 'Vital', 'type': 'Adjectives', 'definition': 'very important'},
{'word': 'White', 'type': 'Adjectives', 'definition': 'the colour of milk'},
{'word': 'Whole', 'type': 'Adjectives', 'definition': 'complete'},
{'word': 'Wrong', 'type': 'Adjectives', 'definition': 'not correct'},
{'word': 'Young', 'type': 'Adjectives', 'definition': 'not old'},   
]

let i = 0, ln = data.length;
for (i;i<ln;i++){
  data[i].id = i+1;
}

var file = fs.createWriteStream('test.txt');
file.on('error', function(err) { Console.log(err) });
data2=JSON.stringify(data)

const content = data2;

fs.writeFile('test.txt', content, err => {
  if (err) {
    console.error(err);
  }
  // file written successfully
});

